# .github/workflows/ci.yml
# Workflow de la Clase 1 — se va construyendo paso a paso

name: CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

# Variables a nivel de workflow completo (disponibles en TODOS los jobs)
env:
  NODE_VERSION: "20"
  APP_NAME: cron-ticker

jobs:
  build:
    runs-on: ubuntu-latest

    # Variables a nivel de job (disponibles en TODOS los steps de este job)
    env:
      BUILD_DIR: dist

    steps:
      - uses: actions/checkout@v4

      - name: Show env local variables
        run: |
          echo "App: ${{ env.APP_NAME }}, Node: ${{ env.NODE_VERSION }}"

      - name: Show env github variables
        run: |
          echo "Node: ${{ vars.APP_VERSION }}"

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ vars.NODE_VERSION }}   # variable del repo

      - name: Build
        run: npm run build
        env:
          APP_VERSION: ${{ vars.APP_VERSION }}     # pasa la var al script build.js


        

